# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-22 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_screenTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(default=0)),
                ('time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_number', models.IntegerField(default=1)),
                ('row', models.IntegerField(default=0)),
                ('column', models.IntegerField(default=0)),
                ('taken', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='seats',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='length',
            new_name='screen_number',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='screen',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='screening_time',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='column',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='movie',
            name='Genre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screen',
            name='columns',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='screen',
            name='rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, primary_key=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
