# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-22 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_delete_screenmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieManager',
        ),
    ]
