# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-22 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_delete_moviemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='screen_number',
            field=models.IntegerField(default=0),
        ),
    ]
