# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-22 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_movie_screen_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_screentime',
            old_name='movie_id',
            new_name='moviee_id',
        ),
    ]
